{
  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/AssociationMapping
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: create-drop
        auto_quote_keyword: true

      defer-datasource-initialization: true

      database-platform: org.hibernate.dialect.MySQLDialect


    server:
      port: 8080


}
